language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

dist: focal

before_script:
  - npm install --no-progress
  - npm install -g npm@latest

script:
  - npm ci

notifications:
  email:
    recipients:
      - jtan896@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
